### ISSUE TITLE
It's on the left

### ISSUE THREAD

**Issue by nitewing76** [MomentumV/MMM-RandomBibleVerse#3] opened 2021-02-27 05:22 UTC
I found this module while searching for a solution to fix the same problem with DailyBibleVerse (and a jQuery error that your module doesn't have).

It's the same issue as [this](https://github.com/arthurgarzajr/MMM-DailyBibleVerse/issues/13), which includes a screenshot.  The solution listed on that page did not work.

To ensure there was no conflicts, I renamed the MM directory and did a fresh install...had the same result. I also moved the clock to the bottom_bar to verify there was not a problem with the core of MM or Electron.

ideas?

**Comment by MomentumV** [comment] 2021-02-27 05:33
I can confirm this is a bug; but I haven't had time to dig in and figure out what's going on. I've seen this behavior myself, though.
It exists in both because I based the core of this module on DailyBibleVerse. I am fairly confident it's some ccs issue.
I spent maybe 10 minutes looking for what was causing it and quickly found that it seemed a bit of a mess and decided to leave well enough alone until I had the main idea working. If I get a chance I'll take a look again.

**Comment by MomentumV** [comment] 2021-02-27 05:35
It does seem to be worse for large screens, I think

**Comment by MomentumV** [comment] 2021-02-27 05:37
I think the whole of the sizing code needs to be re-done.

**Comment by nitewing76** [comment] 2021-02-27 07:25
Ok, I hope you figure it out because I prefer the rotating verses, instead of once a day.

**Comment by MomentumV** [comment] 2021-03-01 13:54
Fixed in Release 1.1.1

I just removed the CSS (from MMM-RandomBibleVerse.css) that specified widths as vh (percent of vertical height) based on different sizing configurations. The same approach will work with the DailyBibleVerse module.

**Closed as completed by MomentumV** 2021-03-01 13:54 UTC
